/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  v1: {
    auth: {
      Login: () => import('#controllers/v1/auth/login_controller'),
      Logout: () => import('#controllers/v1/auth/logout_controller'),
      Register: () => import('#controllers/v1/auth/register_controller'),
    },
    users: {
      Me: () => import('#controllers/v1/users/me_controller'),
    },
  },
}
