/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  v1: {
    auth: {
      Login: () => import('#controllers/v1/auth/login_controller'),
      Logout: () => import('#controllers/v1/auth/logout_controller'),
      Register: () => import('#controllers/v1/auth/register_controller'),
    },
    brands: {
      Destroy: () => import('#controllers/v1/brands/destroy_controller'),
      Index: () => import('#controllers/v1/brands/index_controller'),
      Show: () => import('#controllers/v1/brands/show_controller'),
      Store: () => import('#controllers/v1/brands/store_controller'),
      Update: () => import('#controllers/v1/brands/update_controller'),
    },
    platforms: {
      Create: () => import('#controllers/v1/platforms/create_controller'),
      Destroy: () => import('#controllers/v1/platforms/destroy_controller'),
      Retrieve: () => import('#controllers/v1/platforms/retrieve_controller'),
    },
    posts: {
      Destroy: () => import('#controllers/v1/posts/destroy_controller'),
      GenerateAi: () => import('#controllers/v1/posts/generate_ai_controller'),
      Index: () => import('#controllers/v1/posts/index_controller'),
      Show: () => import('#controllers/v1/posts/show_controller'),
      Store: () => import('#controllers/v1/posts/store_controller'),
      Update: () => import('#controllers/v1/posts/update_controller'),
    },
    scheduledPosts: {
      Destroy: () => import('#controllers/v1/scheduled_posts/destroy_controller'),
      Index: () => import('#controllers/v1/scheduled_posts/index_controller'),
      Show: () => import('#controllers/v1/scheduled_posts/show_controller'),
      Store: () => import('#controllers/v1/scheduled_posts/store_controller'),
      Update: () => import('#controllers/v1/scheduled_posts/update_controller'),
    },
    socialAccounts: {
      Destroy: () => import('#controllers/v1/social_accounts/destroy_controller'),
      Index: () => import('#controllers/v1/social_accounts/index_controller'),
      Show: () => import('#controllers/v1/social_accounts/show_controller'),
      Store: () => import('#controllers/v1/social_accounts/store_controller'),
    },
    users: {
      Me: () => import('#controllers/v1/users/me_controller'),
      oauth: {
        mastodon: {
          Callback: () => import('#controllers/v1/users/oauth/mastodon/callback_controller'),
          Redirect: () => import('#controllers/v1/users/oauth/mastodon/redirect_controller'),
        },
      },
      Permission: () => import('#controllers/v1/users/permission_controller'),
    },
  },
}
